### ISSUE TITLE
Digg paginator fail

### ISSUE THREAD

**Issue by jankopacek** [aldryn/aldryn-common#11]
Sometimes fall in: 
can only concatenate list (not "range") to list
```
279.            page.page_range = functools.reduce(lambda x, y: x+((x and y) and [False])+y,
                [page.leading_range, page.main_range, page.trailing_range])
```
```
y 	range(15, 17)

x 	[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```
Missconfiguration?

**Comment by vstoykov** [comment]
As I see there is some problem with Python3 support (you are using Python 3 right?)

**Comment by jankopacek** [comment]
Yes, for now I solved it with retyping like 
page.page_range = functools.reduce(lambda x, y:list(x)+((list(x) and list(y)) and [False])+list(y),
             [page.leading_range, page.main_range, page.trailing_range])

**Comment by trawick** [comment]
still broken in master, submitting pull request "soon"
